export const EXAMPLE_USER_ACTION = 'EXAMPLE_USER_ACTION'
export const EXAMPLE_REQUEST = 'EXAMPLE_REQUEST'
export const EXAMPLE_SUCCESS = 'EXAMPLE_SUCCESS'
export const EXAMPLE_FAILURE = 'EXAMPLE_FAILURE'